name: Node.js CI

### github.ref
# tags   refs/tags/v0.0.1
# master refs/heads/master

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  ####### Print: Prints some context relating to the job to make future debugging easier
  print:
    name: Print context
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Print context 🎉
        env:
          GH_REF: ${{ github.ref }}
        run: |
          echo "GH_REF: ${GH_REF}"
  ####### Lint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd serverless-blog
      - run: yarn install
      - run: yarn lint

  ####### Unit tests
  unit_tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd serverless-blog
      - run: yarn install
      - run: yarn test
